(function(){
  "use strict";

  if (window.history && window.history.pushState ) {
    App.Router.reopen({
      location: 'history'
    });
  }

  App.Router.map(function() {

    // generated by ember-generate --scaffold
    this.resource('events');
    this.resource('event', {path: '/event/:pageUrl'});
    // end generated routes


    // generated by ember-generate --scaffold
    // this.resource('newsposts');
    // this.resource('newspost', {path: '/newspost/:urlId'});
    // end generated routes


    // generated by ember-generate --scaffold
    this.resource('performers');
    this.resource('performer', {path: '/performer/:pageUrl'});
    this.resource('shows');
    this.resource('show', {path: '/show/:pageUrl'});
    // this.route('edit_performer', {path: '/performers/:performer_id/edit'});
    // this.route('new_performer', {path: '/performers/new'});
    // end generated routes

    this.route('sponsors');
    this.route('schedule');
    this.route('thursday_schedule');
    this.route('friday_schedule');
    this.route('saturday_schedule');
    this.route('sunday_schedule');

    this.route('venues');
    this.resource('venue', {path: '/venue/:pageUrl'});
    this.route('history');
    this.route('press');
    this.route('contact');
    this.route('tickets');
    this.route('faqs');


    this.route('fourOhFour', { path: '*path' });


  });

  App.Router.reopen({
    didTransition: function(infos) {
      this._super(infos);


      Ember.run.next(function(){
        try {
        ga(
          'send',
          'pageview',
          window.location.protocol +'//' + window.location.hostname + window.location.pathname + window.location.search
        );
      }
      catch(e){}
      });
    }
  });

  Ember.Route.reopen({
    render: function() {
      this._super();
      window.scrollTo(0, 0);
      $('[data-type="image"]').each(function() {
        $(this).attr('src',$(this).data('src'));
      });
    },
    activate: function() {
      this._super();
      if (this.get('title')) {
        document.title = this.get('title') + ' | Bridgetown Comedy Festival';
      } else {
        document.title = 'Bridgetown Comedy Festival';
      }
    },
    deactivate: function() {
      if ($(".navbar .navbar-collapse.collapse.in").length) {
        $(".navbar-toggle").not(".collapsed").click();
      }
    },
    loadAllData: function() {
      return Ember.RSVP.hash({
        venues: this.store.find('venue'),
        events: this.store.find('event'),
        performers: this.store.find('performer'),
        shows: this.store.find('show')
      });
    }
  });

  App.fourOhFourRoute = Ember.Route.extend({
    renderTemplate: function() {this.render('four_oh_four');},
  });

}());
